
- name : Configure consul servers
  hosts: frontend
  become: yes
  become_user: root
  tasks:
    - name: Install Packages
      yum:
        name:
        - httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes